# path to a directory with all packages
storage: ../tmp/local-registry/storage

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  "**":
    access: public
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to npm registry
    proxy: npmjs

  "@cruncher/app":
    access: public
    publish: false
    unpublish: false

# log settings
log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: false
